let nTypeId = 0 // yes this should start at 0 not -1, because for whatever reason nTypeId++ returns 0 not 1 like i expected, so yes our first enum value will be 0 as desired
let textureId = 0
export const textureIds = {
	none: textureId++,
	dancingBaby: textureId++,
	rapidPunches: textureId++,
	fireBarrel: textureId++,
	rectangle: textureId++,
	_22PistolPickup: textureId++,
	pistolPickup: textureId++,
	shotgunPickup: textureId++,
	_22PistolOverlay: textureId++,
	pistolOverlay: textureId++,
	shotgunOverlay: textureId++,
	wizardStaff: textureId++,
	tracer1: textureId++,
	tracer2: textureId++,
	tracer3: textureId++,
	grenade1: textureId++,
	chud: textureId++,
	racistMan: textureId++,
	amerimutt1: textureId++,
	amerimutt2: textureId++,
	amerimutt3: textureId++,
	tranny1: textureId++,
	tranny2: textureId++,
	synthwaveSwastika: textureId++,
	tree: textureId++,
	rock: textureId++,
	jew: textureId++,
	tyrone: textureId++,
	pitbull: textureId++,
	naziPepe: textureId++,
	moneyBag: textureId++,
	rapidBlast: textureId++,
	tileset1: textureId++,
	tileset2: textureId++,
	tileset3: textureId++,
	tntBox: textureId++,
	ar15Pickup: textureId++,
	ar15Overlay: textureId++,
	doomPepe: textureId++,
	honkler: textureId++,
	soyjak1: textureId++,
	soyjak2: textureId++,
	tndSquirrel: textureId++,
}
export const textureIdToString = new Map([
	[textureIds.none, ''],
	[textureIds._22PistolOverlay, '22-pistol-overlay'],
	[textureIds.pistolOverlay, 'pistol-overlay'],
	[textureIds.shotgunOverlay, 'shotgun-overlay'],
	[textureIds.wizardStaff, 'wizard-staff'],
	[textureIds.dancingBaby, 'dancing-baby'],
	[textureIds.rapidPunches, 'rapid-punches'],
	[textureIds.fireBarrel, 'fire-barrel'],
	[textureIds.rectangle, 'rectangle'],
	[textureIds._22PistolPickup, '22-pistol-pickup'],
	[textureIds.pistolPickup, 'pistol-pickup'],
	[textureIds.shotgunPickup, 'shotgun-pickup'],
	[textureIds.tracer1, 'tracer-1'],
	[textureIds.tracer2, 'tracer-2'],
	[textureIds.tracer3, 'tracer-3'],
	[textureIds.grenade1, 'grenade-1'],
	[textureIds.chud, 'chud'],
	[textureIds.racistMan, 'racist-man'],
	[textureIds.amerimutt1, 'amerimutt-1'],
	[textureIds.amerimutt2, 'amerimutt-2'],
	[textureIds.amerimutt3, 'amerimutt-3'],
	[textureIds.tranny1, 'tranny-1'],
	[textureIds.tranny2, 'tranny-2'],
	[textureIds.synthwaveSwastika, 'synthwave-swastika'],
	[textureIds.tree, 'tree'],
	[textureIds.rock, 'rock'],
	[textureIds.jew, 'jew'],
	[textureIds.tyrone, 'tyrone'],
	[textureIds.pitbull, 'pitbull'],
	[textureIds.naziPepe, 'nazi-pepe'],
	[textureIds.moneyBag, 'money-bag'],
	[textureIds.rapidBlast, 'rapid-blast'],
	[textureIds.tileset1, 'tileset-1'],
	[textureIds.tileset2, 'tileset-2'],
	[textureIds.tileset3, 'tileset-3'],
	[textureIds.tntBox, 'tnt-box'],
	[textureIds.ar15Overlay, 'ar15-overlay'],
	[textureIds.ar15Pickup, 'ar15-pickup'],
	[textureIds.doomPepe, 'doom-pepe'],
	[textureIds.honkler, 'honkler'],
	[textureIds.soyjak1, 'soyjak-1'],
	[textureIds.soyjak2, 'soyjak-2'],
	[textureIds.tndSquirrel, 'tnd-squirrel']
])
export const stringToTextureId = new Map(Array.from(textureIdToString, a => a.reverse()))
export const overlayBit = {
	fire: 0,
	// the rest dont exist yet. it can go up to 15. 0-15. correlates to the overlays property the visuals entity
}
export const npcAction = {
	wander: 0,
	attackNearestPlayer: 1,
	runRandomlyOnFire: 2,
	runFromPlayers: 3,
}
export const NType = {
	NULL: nTypeId++,
	// entities
	VisualsEntity: nTypeId++,
	FireDamageAreaEntity: nTypeId++,
	// commands
	AbilityCommand: nTypeId++,
	ChatCommand: nTypeId++,
	UICommand: nTypeId++,
	WASDCommand: nTypeId++,
	PointerPositionCommand: nTypeId++,
	DropItemCommand: nTypeId++,
	KeyDownCommand: nTypeId++,
	// messages
	ChangePlayerObjectMessage: nTypeId++,
	LoseAbilityMessage: nTypeId++,
	ObtainAbilityMessage: nTypeId++,
	ChatMessage: nTypeId++,
	PlaySoundMessage: nTypeId++,
	PlayerCountMessage: nTypeId++,
	AllPlayerPositionsMessage: nTypeId++,
}
export const wasdStates = {
	released: 0,
	north: 1,
	northeast: 2,
	east: 3,
	southeast: 4,
	south: 5,
	southwest: 6,
	west: 7,
	northwest: 8,
}
export const uiActions = {
	clickedPlayButton: 0,
	clickedAvatarSelect: 1,
}
export const abilityState = {
	none: 0,
	once: 1,
	repeat: 2,
	stop: 3
}
export const directions = {
	east: 0,
	southeast: 1,
	south: 2,
	southwest: 3,
	west: 4,
	northwest: 5,
	north: 6,
	northeast: 7,
}
export const soundIds = {
	reload1: 0,
	ayoWtf: 1,
	youFuckingChud: 2,
	youStupidChud: 3,
}